name: Generated APK AAB (Upload)

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: Build Lab

on:

  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK or Bundle based on selectedBuildVariant and isAndroidAppBundle
      - name: Build app
        run: |
          if [ "${{ matrix.build_variant }}" = "Debug" ]; then
            if [ "${{ matrix.is_bundle }}" = "true" ]; then
              ./gradlew assembleDebug bundleDebug
            else
              ./gradlew assembleDebug
            fi
          else
            if [ "${{ matrix.is_bundle }}" = "true" ]; then
              ./gradlew ${{ env.main_project_module }}:bundleRelease
            else
              ./gradlew assembleRelease
            fi
          fi
        env:
          BUILD_VARIANT: ${{ matrix.build_variant }}
          IS_BUNDLE: ${{ matrix.is_bundle }}

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK/Bundle
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - ${{ env.BUILD_VARIANT }} ${{ env.IS_BUNDLE && 'bundle' }} generated
          path: ${{ env.main_project_module }}/build/outputs/${{ env.BUILD_VARIANT == 'Release' && env.IS_BUNDLE && 'bundle' || 'apk' }}/${{ env.BUILD_VARIANT | lower }}/                                                             
          
    strategy:
      matrix:
        build_variant: ["Debug", "Release"]
        is_bundle: [true, false]
