name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Set up Gradle
      uses: gradle/setup-gradle@v1
      with:
        gradle-version: 7.3.3

    - name: Build with Gradle
      run: ./gradlew build
